from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
import subprocess
import uuid
import os
import glob

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def root():
    return {"status": "backend running"}

class PromptRequest(BaseModel):
    prompt: str
    num_steps: int = 20

@app.post("/generate/")
def generate(request: PromptRequest):
    prompt = request.prompt
    num_steps = request.num_steps

    output_dir = "outputs"
    os.makedirs(output_dir, exist_ok=True)

    # Remove previous images
    for f in glob.glob(os.path.join(output_dir, "*.png")):
        os.remove(f)

    # Command to run your Qualcomm SD model
    command = [
        "python", "demo.py",
        "--prompt", prompt,
        "--num-steps", str(num_steps),
        "--output-dir", output_dir
    ]

    # Run demo.py
    subprocess.run(command, check=True)

    # Find the output image created inside the output_dir
    generated_images = glob.glob(os.path.join(output_dir, "*.png"))
    if not generated_images:
        raise RuntimeError("No image generated by demo.py")

    image_path = generated_images[0]

    # Return the image
    return FileResponse(image_path, media_type="image/png")
